/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityTab: typeof import('./src/components/mytasks/ActivityTab.vue')['default']
    AnalyticsChartCard: typeof import('./src/components/AnalyticsChartCard.vue')['default']
    AnalyticsStatTile: typeof import('./src/components/AnalyticsStatTile.vue')['default']
    AppSidebar: typeof import('./src/components/Layouts/AppSidebar.vue')['default']
    AttachmentsTab: typeof import('./src/components/taskdetail/AttachmentsTab.vue')['default']
    CalendarView: typeof import('./src/components/project-tasks/CalendarView.vue')['default']
    CreateProjectDialog: typeof import('./src/components/CreateProjectDialog.vue')['default']
    CreateTaskDialog: typeof import('./src/components/CreateTaskDialog.vue')['default']
    CreateWorkspaceDialog: typeof import('./src/components/CreateWorkspaceDialog.vue')['default']
    DatePill: typeof import('./src/components/DatePill.vue')['default']
    DesktopLayout: typeof import('./src/components/Layouts/DesktopLayout.vue')['default']
    FileIcon: typeof import('./src/components/taskdetail/FileIcon.vue')['default']
    FilterChip: typeof import('./src/components/FilterChip.vue')['default']
    FilterSection: typeof import('./src/components/FilterSection.vue')['default']
    GettingStartedCard: typeof import('./src/components/GettingStartedCard.vue')['default']
    HistoryTab: typeof import('./src/components/taskdetail/HistoryTab.vue')['default']
    KanbanCard: typeof import('./src/components/project-tasks/KanbanCard.vue')['default']
    KanbanView: typeof import('./src/components/project-tasks/KanbanView.vue')['default']
    ListView: typeof import('./src/components/project-tasks/ListView.vue')['default']
    MentionList: typeof import('./src/components/editor/MentionList.vue')['default']
    MilestonesTab: typeof import('./src/components/project/MilestonesTab.vue')['default']
    ModulesTab: typeof import('./src/components/project/ModulesTab.vue')['default']
    MyTaskRow: typeof import('./src/components/MyTaskRow.vue')['default']
    OrbitMark: typeof import('./src/components/OrbitMark.vue')['default']
    OverviewTab: typeof import('./src/components/project/OverviewTab.vue')['default']
    PageTree: typeof import('./src/components/PageTree.vue')['default']
    PageTreeRow: typeof import('./src/components/PageTreeRow.vue')['default']
    PillPlaceholder: typeof import('./src/components/PillPlaceholder.vue')['default']
    ProfileCard: typeof import('./src/components/mytasks/ProfileCard.vue')['default']
    ProjectPagesTab: typeof import('./src/components/ProjectPagesTab.vue')['default']
    ProjectsSidebarSection: typeof import('./src/components/ProjectsSidebarSection.vue')['default']
    ProjectTasksTab: typeof import('./src/components/ProjectTasksTab.vue')['default']
    RichEditor: typeof import('./src/components/editor/RichEditor.vue')['default']
    RichEmptyState: typeof import('./src/components/project/RichEmptyState.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsTab: typeof import('./src/components/project/SettingsTab.vue')['default']
    SidebarLink: typeof import('./src/components/SidebarLink.vue')['default']
    SlashCommandList: typeof import('./src/components/editor/SlashCommandList.vue')['default']
    SpreadsheetView: typeof import('./src/components/project-tasks/SpreadsheetView.vue')['default']
    SummaryTab: typeof import('./src/components/mytasks/SummaryTab.vue')['default']
    TaskDetailPanel: typeof import('./src/components/TaskDetailPanel.vue')['default']
    TaskDetailSidebarRow: typeof import('./src/components/TaskDetailSidebarRow.vue')['default']
    TaskListTab: typeof import('./src/components/mytasks/TaskListTab.vue')['default']
    TaskRow: typeof import('./src/components/TaskRow.vue')['default']
    ToolbarButton: typeof import('./src/components/editor/ToolbarButton.vue')['default']
    TransitionsTab: typeof import('./src/components/taskdetail/TransitionsTab.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
    UserDropdown: typeof import('./src/components/UserDropdown.vue')['default']
    ViewsTab: typeof import('./src/components/project/ViewsTab.vue')['default']
    WorkloadTile: typeof import('./src/components/mytasks/WorkloadTile.vue')['default']
    WorkspaceOnboardingDialog: typeof import('./src/components/WorkspaceOnboardingDialog.vue')['default']
  }
}
